blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/jawwad-ali/ai-customer-support-agent/issues
    about: Ask questions or discuss ideas by opening an issue
